const softcoreADI = ['animal fat',
  'animal fats and oils',
  'animal fiber',
  'animal hair',
  'antlers',
  'bear bile',
  'bee pollen',
  'beeswax',
  'blood',
  'bone ash',
  'bone char',
  'bone meal',
  'broth',
  'carmine',
  'carotene',
  'casein',
  'caseinate',
  'cashmere',
  'castor',
  'castoreum',
  'caviar',
  'cheese',
  'cochineal',
  'confectioner\'s glaze',
  'cricket flour',
  'custard',
  'down',
  'egg',
  'eggnog',
  'eggs',
  'escargot',
  'feathers',
  'fish',
  'fishmeal',
  'fur',
  'gallstones',
  'game',
  'gelatin',
  'ghee',
  'honey',
  'honeycomb',
  'horns',
  'horse oil',
  'horsehair',
  'insects',
  'ivory',
  'lactose',
  'lard',
  'lardon',
  'leather',
  'livestock',
  'manure',
  'mayonnaise',
  'meat',
  'milk',
  'mink',
  'mink lashes',
  'mink oil',
  'musk',
  'nautilus',
  'offal',
  'organ',
  'organs',
  'pearl',
  'quarry',
  'rennet',
  'royal jelly',
  'scales',
  'shark',
  'shellac',
  'shellfish',
  'silk',
  'skin',
  'skins',
  'skunk oil',
  'snail',
  'snails',
  'snake wine',
  'sponge',
  'stock',
  'suede',
  'tallow',
  'tortoise shell',
  'tortoiseshell',
  'venom',
  'whale oil',
  'whey',
  'wool'
];
const allDefADI = [
  'afterbirth',
  'albumen',
  'albumin',
  'alligator skin',
  'ambergris',
  'amerchol l101',
  'angora',
  'animal bone ash',
  'animal fat',
  'animal fats and oils',
  'animal fiber',
  'animal hair',
  'antlers',
  'arachnids',
  'bear bile',
  'bee pollen',
  'bee products',
  'beeswax',
  'blood',
  'boar bristles',
  'bone',
  'bone ash',
  'bone char',
  'bone meal',
  'calcium caseinate',
  'calfskin',
  'carmine',
  'carminic acid',
  'casein',
  'caseinate',
  'cashmere',
  'castor',
  'castoreum',
  'catgut',
  'caviar',
  'cera flava',
  'cheese',
  'cochineal',
  'cod liver oil',
  'collagen',
  "confectioner's glaze",
  'cricket flour',
  'donkey milk',
  'down',
  'egg',
  'egg protein',
  'eggnog',
  'eggs',
  'ejaculate',
  'elastin',
  'emu oil',
  'escargot',
  'feathers',
  'fish',
  'fish liver oil',
  'fish oil',
  'fish scales',
  'fishmeal',
  'fur',
  'game',
  'gelatin',
  'ghee',
  'hard roe',
  'hide glue',
  'honey',
  'honeycomb',
  'horns',
  'horse oil',
  'horsehair',
  'hydrolyzed animal protein',
  'hydrolyzed milk protein',
  'insects',
  'isinglass',
  'isopropyl lanolate',
  'lactose',
  'laneth',
  'lanogene',
  'lanolin',
  'lanolin acids',
  'lanolin alcohol',
  'lard',
  'leather',
  'manure',
  'marine oil',
  'meat',
  'milk',
  'milk protein',
  'mink',
  'mink lashes',
  'mink oil',
  'offal',
  'organ',
  'organs',
  'pearl',
  'pearl essence',
  'pepsin',
  'placenta',
  'propolis',
  'quarry',
  'rennet',
  'rennin',
  'resinous glaze',
  'royal jelly',
  'scales',
  'schmaltz',
  'sea turtle oil',
  'shark',
  'shark liver oil',
  'shellac',
  'shellfish',
  'silk',
  'silk powder',
  'skin',
  'skins',
  'skunk oil',
  'snail',
  'snails',
  'snake wine',
  'sodium caseinate',
  'sodium tallowate',
  'soft roe',
  'sperm oil',
  'sponge',
  'suet',
  'tallow',
  'tallow acid',
  'tallow amide',
  'tallow amine',
  'tallow fatty alcohol',
  'tallow glycerides',
  'tallow imidazoline',
  'talloweth-6',
  'urea',
  'uric acid',
  'urine',
  'venom',
  'whale oil',
  'whey',
  'wool',
  'wool fat',
  'wool wax'
];
const allProbADI = [
  'chitosan',
  'cholesterol',
  'cholesterin',
  'duodenum substance',
  'duodenum substances',
  'estradiol',
  'guanine',
  'polypeptides',
  'pristane',
  'lanosterols',
  'keratin',
  'methionine',
  'vitamin d3',
];
const allMaybeADI = [
  'adrenaline',
  'alanine',
  'alcloxa',
  'aldioxa',
  'aliphatic alcohol',
  'allantoin',
  'alpha-hydroxy acids',
  'ambrosia',
  'amino acids',
  'aminosuccinate acid',
  'arachidonic acid',
  'arachidyl proprionate',
  'beta carotene',
  'biotin',
  'broth',
  'calciferol',
  'capryl betaine',
  'caprylamine oxide',
  'caprylic acid',
  'caprylic triglyceride',
  'carbamide',
  'carotene',
  'cerebrosides',
  'cetyl alcohol',
  'cetyl palmitate',
  'choline bitartrate',
  'civet',
  'civet oil',
  'coral rock',
  'corticosteroid',
  'cortisone',
  'custard',
  'cysteine',
  'l-form',
  'cystine',
  'dexpanthenol',
  'diglycerides',
  'dimethyl stearamine',
  'dyes',
  'ergocalciferol',
  'ergosterol',
  'estrogen',
  'gallstones',
  'glucose tyrosinase',
  'glycerides',
  'glycerin',
  'glycerol',
  'glyceryls',
  'glycreth-26',
  'gribenes',
  'guano',
  'hyaluronic acid',
  'hydrocortisone',
  'imidazolidinyl urea',
  'insulin',
  'isopropyl myristate',
  'isopropyl palmitate',
  'ivory',
  'l. cysteine',
  'lactic acid',
  'lardon',
  'lecithin',
  'linoleic acid',
  'linoleic acids',
  'lipase',
  'lipids',
  'lipoids',
  'livestock',
  'mayonnaise',
  'monoglycerides',
  'musk',
  'myristal ether sulfate',
  'myristic acid',
  'myristyls',
  'natural glaze',
  'nautilus',
  'nucleic acids',
  'ocenol',
  'octyl dodecanol',
  'oleic acid',
  'oleths',
  'oleyl alcohol',
  'oleyl arachidate',
  'oleyl imidazoline',
  'oleyl myristate',
  'oleyl oleate',
  'oleyl stearate',
  'palmitamide',
  'palmitamine',
  'palmitate',
  'palmitic acid',
  'panthenol',
  'panthenyl',
  'polyglycerol',
  'polysorbates',
  'progesterone',
  'provitamin a',
  'provitamin b-5',
  'provitamin d-2',
  'provitamin d2',
  'pure food glaze',
  'rambak',
  'retinol',
  'ribonucleic acid',
  'rinds',
  'rna',
  'sable brushes',
  'scratchings',
  'sea shells',
  'sheepskin',
  'sodium steroyl lactylate',
  'spermaceti',
  'squalane',
  'squalene',
  'stearamide',
  'stearamine',
  'stearamine oxide',
  'stearates',
  'stearic acid',
  'stearic hydrazide',
  'stearin',
  'stearone',
  'stearoxytrimethylsilane',
  'stearoyl lactylic acid',
  'stearyl acetate',
  'stearyl alcohol',
  'stearyl betaine',
  'stearyl caprylate',
  'stearyl citrate',
  'stearyl glycyrrhetinate',
  'stearyl heptanoate',
  'stearyl imidazoline',
  'stearyl octanoate',
  'stearyl stearate',
  'stearyldimethyl amine',
  'steroids',
  'sterols',
  'stock',
  'suede',
  'tortoise shell',
  'tortoiseshell',
  'triterpene alcohols',
  'turtle oil',
  'tyrosine',
  'vitamin a',
  'vitamin b factor',
  'vitamin b-complex factor',
  'vitamin b12',
  'vitamin d',
  'vitamin d2',
  'vitamin h',
];

export { softcoreADI, allDefADI, allProbADI, allMaybeADI };